import React, { useRef } from 'react';
import { theme } from '../../styles/theme';
import { Button } from './Button';
import { useStore } from '../../utils/store';
import { adaptAnalysisData, ensureSummary } from '../../utils/dataAdapter';

interface FileUploaderProps {
  onFileLoad?: (data: any) => void;
}

export const FileUploader: React.FC<FileUploaderProps> = ({ onFileLoad }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { setAnalysisData, setIsLoading } = useStore();

  const handleFileClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      setIsLoading(true);

      // Check if it's a JSON file
      if (!file.name.endsWith('.json')) {
        alert('Please select a JSON file (e.g., comprehensive_analysis.json)');
        return;
      }

      // Read the file
      const text = await file.text();
      const rawData = JSON.parse(text);

      // Validate data structure
      if (!rawData.metadata) {
        alert('Invalid analysis file format. Please select a valid comprehensive_analysis.json file.');
        return;
      }

      // Adapt the data to match GUI expectations
      const adaptedData = adaptAnalysisData(rawData);
      const finalData = ensureSummary(adaptedData);

      // Load the data
      setAnalysisData(finalData);
      
      if (onFileLoad) {
        onFileLoad(finalData);
      }

      // Show success message
      const projectName = finalData.metadata?.project_name || 'Project';
      alert(`✅ Successfully loaded: ${projectName}\n\n` +
            `Files scanned: ${finalData.files_scanned?.length || 0}\n` +
            `Total issues: ${finalData.summary?.total_issues || 0}\n` +
            `Risk level: ${finalData.risk_level || 'UNKNOWN'}`);

    } catch (error) {
      console.error('Error loading file:', error);
      alert('❌ Error loading file. Please make sure it\'s a valid JSON file generated by the security analyzer.');
    } finally {
      setIsLoading(false);
      // Reset input so the same file can be selected again
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  return (
    <div>
      <input
        ref={fileInputRef}
        type="file"
        accept=".json,application/json"
        onChange={handleFileChange}
        style={{ display: 'none' }}
      />
      <Button
        variant="primary"
        size="lg"
        icon="📂"
        onClick={handleFileClick}
        fullWidth
      >
        Browse & Load Analysis File
      </Button>
      
      <p style={{
        marginTop: theme.spacing.sm,
        fontSize: theme.typography.fontSize.sm,
        color: theme.colors.text.secondary,
        textAlign: 'center',
      }}>
        Select comprehensive_analysis.json or output JSON file
      </p>
    </div>
  );
};

